# models.py
from datetime import datetime
from sqlalchemy import JSON, Column, DateTime, ForeignKey, Integer, String, LargeBinary
from database import Base
from sqlalchemy.orm import relationship


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String, unique=True, index=True)
    email = Column(String, unique=True, index=True)
    hashed_password = Column(String)

    # link to datasets
    datasets = relationship("Dataset", back_populates="owner")

    # relationships for all model tables
    models = relationship("DefaultModel", back_populates="user", cascade="all, delete")



    # saved plots generated by the server
    plots = relationship("Plot", back_populates="user")


class Dataset(Base):
    __tablename__ = "datasets"

    id = Column(Integer, primary_key=True, index=True)
    filename = Column(String, unique=True, index=True)
    owner_id = Column(Integer, ForeignKey("users.id"))

    owner = relationship("User", back_populates="datasets")
    plots = relationship("Plot", back_populates="dataset")


class DefaultModel(Base):
    __tablename__ = "default_model"

    id = Column(Integer, primary_key=True, index=True)
    model_type = Column(String, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    dataset = Column(String, index=True)
    parameters = Column(JSON)  # store model parameters if needed
    metrics = Column(JSON)     # store performance metrics
    created_at = Column(DateTime, default=datetime.utcnow)

    user = relationship("User", back_populates="models")





# New model to store server-rendered plots as binary blobs
class Plot(Base):
    __tablename__ = "plots"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    dataset_id = Column(Integer, ForeignKey("datasets.id"), index=True, nullable=True)
    name = Column(String, index=True)  # e.g., "roc_curve", "confusion_matrix"
    image = Column(LargeBinary)  # PNG bytes

    user = relationship("User", back_populates="plots")
    dataset = relationship("Dataset", back_populates="plots")
